# Generated by Django 4.2.5 on 2025-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiginetOntsMigrationDB',
            fields=[
                ('register_id', models.TextField(max_length=150, primary_key=True, serialize=False)),
                ('pon', models.TextField(max_length=150)),
                ('host', models.TextField(max_length=150)),
            ],
        ),
    ]
