# Generated by Django 4.2.5 on 2025-11-07 17:08

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('migration_onts_diginet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diginetontsmigrationdb',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='diginetontsmigrationdb',
            name='serial_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
