# Generated by Django 4.2.9 on 2024-01-18 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsInfos',
            fields=[
                ('tab_id', models.TextField(max_length=150, primary_key=True, serialize=False)),
                ('source_gpon', models.JSONField(null=True)),
                ('unchanged_devices', models.TextField(null=True)),
                ('selected_devices', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
