# Generated by Django 4.2.9 on 2024-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_sms_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsinfos',
            name='unchanged_devices',
        ),
        migrations.AddField(
            model_name='smsinfos',
            name='contacts',
            field=models.JSONField(null=True),
        ),
    ]
