# Generated by Django 4.2.5 on 2024-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager', '0002_alter_attenuatordb_attenuations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attenuatordb',
            name='source_gpon',
            field=models.JSONField(null=True),
        ),
    ]
