# Generated by Django 4.2.5 on 2024-01-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager', '0003_alter_attenuatordb_source_gpon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attenuatordb',
            name='attenuations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='commands_url',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='destination_gpon',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='search_mode',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='selected_devices',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='source_gpon',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='unchanged_devices',
            field=models.TextField(default=None, null=True),
        ),
    ]
