# Generated by Django 4.2.5 on 2024-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager', '0006_alter_attenuatordb_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attenuatordb',
            name='attenuations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='commands_url',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='destination_gpon',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='file_name',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='search_mode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='selected_devices',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='source_gpon',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='unchanged_devices',
            field=models.TextField(null=True),
        ),
    ]
