# Generated by Django 4.2.5 on 2024-01-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attenuatordb',
            name='attenuations',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='commands_url',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='destination_gpon',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='file_name',
            field=models.TextField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='search_mode',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='selected_devices',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='source_gpon',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='attenuatordb',
            name='unchanged_devices',
            field=models.TextField(default=None),
        ),
    ]
