# Generated by Django 4.2.5 on 2024-02-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0007_alter_attenuatordb_attenuations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attenuatordb',
            old_name='tab_id',
            new_name='register_id',
        ),
        migrations.RenameField(
            model_name='attenuatordb',
            old_name='unchanged_devices',
            new_name='unchanged_onts',
        ),
    ]
