# Generated by Django 4.2.5 on 2024-03-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0008_rename_tab_id_attenuatordb_register_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attenuatordb',
            name='search_mode',
        ),
    ]
