# Generated by Django 4.2.5 on 2024-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0009_remove_attenuatordb_search_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenuatordb',
            name='logs',
            field=models.JSONField(null=True),
        ),
    ]
