# Generated by Django 4.2.5 on 2024-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0012_rename_original_configuration_attenuatordb_source_port_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenuatordb',
            name='rollback_commands_url',
            field=models.JSONField(null=True),
        ),
    ]
