# Generated by Django 4.2.5 on 2024-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0013_attenuatordb_rollback_commands_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenuatordb',
            name='commands_applied',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='attenuatordb',
            name='rollback_commands_applied',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='attenuatordb',
            name='rollback_logs',
            field=models.JSONField(null=True),
        ),
    ]
