# Generated by Django 4.2.5 on 2024-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0015_attenuatordb_date_commands_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenuatordb',
            name='commands_removed',
            field=models.BooleanField(default=False),
        ),
    ]
