# Generated by Django 4.2.5 on 2024-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attenuations_manager_app', '0016_attenuatordb_commands_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attenuatordb',
            name='user',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
