# Generated by Django 4.2.5 on 2023-10-17 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenceinfo',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 19, 5, 3, 315305)),
        ),
    ]
