# Generated by Django 4.2.5 on 2023-10-17 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0004_alter_maintenceinfo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenceinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
