# Generated by Django 4.1.5 on 2023-10-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0005_alter_maintenceinfo_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintenceInfo',
            new_name='MaintenanceInfo',
        ),
    ]
