# Generated by Django 4.2.5 on 2023-10-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0008_maintenanceinfo_url_commands'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceinfo',
            old_name='url_commands',
            new_name='commands_url',
        ),
    ]
