# Generated by Django 4.2.5 on 2024-01-30 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commands_generator_app", "0009_rename_url_commands_maintenanceinfo_commands_url"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MaintenanceInfo",
            new_name="GeneratorDB",
        ),
    ]
