# Generated by Django 4.2.5 on 2024-01-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0010_rename_maintenanceinfo_generatordb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatordb',
            name='commands_url',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generatordb',
            name='destination_gpon',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generatordb',
            name='file_name',
            field=models.TextField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='generatordb',
            name='selected_devices',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generatordb',
            name='source_gpon',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='generatordb',
            name='unchanged_devices',
            field=models.TextField(default=None, null=True),
        ),
    ]
