# Generated by Django 4.2.5 on 2024-02-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0012_alter_generatordb_commands_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatordb',
            old_name='tab_id',
            new_name='register_id',
        ),
        migrations.RenameField(
            model_name='generatordb',
            old_name='unchanged_devices',
            new_name='unchanged_onts',
        ),
    ]
