# Generated by Django 4.2.5 on 2024-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0013_rename_tab_id_generatordb_register_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatordb',
            name='logs',
            field=models.JSONField(null=True),
        ),
    ]
