# Generated by Django 4.2.5 on 2024-04-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0015_generatordb_original_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatordb',
            old_name='original_configuration',
            new_name='source_port_config',
        ),
    ]
