# Generated by Django 4.2.5 on 2024-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0017_generatordb_rollback_commands_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatordb',
            name='rollback_logs',
            field=models.JSONField(null=True),
        ),
    ]
