# Generated by Django 4.2.5 on 2024-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0018_generatordb_rollback_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatordb',
            name='commands_applied',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='generatordb',
            name='rollback_commands_applied',
            field=models.BooleanField(null=True),
        ),
    ]
