# Generated by Django 4.2.5 on 2024-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0020_generatordb_date_commands_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatordb',
            name='commands_removed',
            field=models.BooleanField(default=False),
        ),
    ]
