# Generated by Django 4.2.5 on 2024-06-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0021_generatordb_commands_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatordb',
            name='user',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
