# Generated by Django 4.2.5 on 2024-06-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator_app', '0022_generatordb_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatordb',
            old_name='user',
            new_name='owner',
        ),
    ]
