# Generated by Django 4.2.5 on 2023-10-17 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenceInfo',
            fields=[
                ('tab_id', models.TextField(max_length=150, primary_key=True, serialize=False)),
                ('file_name', models.TextField(blank=True, max_length=150)),
                ('source_gpon', models.JSONField(blank=True)),
                ('destination_gpon', models.JSONField(blank=True)),
                ('unchanged_devices', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 17, 19, 2, 5, 679929))),
            ],
        ),
    ]
