# Generated by Django 4.2.5 on 2023-10-17 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator', '0002_alter_maintenceinfo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenceinfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 19, 23, 1, 443293), null=True),
        ),
        migrations.AlterField(
            model_name='maintenceinfo',
            name='destination_gpon',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenceinfo',
            name='file_name',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='maintenceinfo',
            name='source_gpon',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenceinfo',
            name='unchanged_devices',
            field=models.TextField(null=True),
        ),
    ]
