# Generated by Django 4.2.5 on 2023-10-17 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands_generator', '0003_alter_maintenceinfo_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenceinfo',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
